In [9]:
import pandas as pd

In [10]:
dotacion = pd.read_excel(r"Bases.xlsx", sheet_name="dotación")

In [11]:
remuneracion = pd.read_excel(r"Bases.xlsx", sheet_name="Remuneración_Venta")

In [12]:
diccionario = pd.read_excel(r"Bases.xlsx", sheet_name="Diccionario_Dpto&Gerencia")

In [13]:
dotacion.head()

,dni,nombre,tienda,vertical,puesto,departamento,fecha_ingreso,fecha_cese,tipo_salida
0,99510741,Diego Elena Ramírez Flores,Plaza Lima Norte,Hogar,Asesor de Ventas,Ventas Hogar,2024-05-22,2026-03-24,Voluntario
1,87326012,Daniela Eduardo Carranza Medina,Plaza Lima Norte,Utiles escolar,Asesor de Ventas,Utiles Escolares,2024-01-28,2026-03-18,Voluntario
2,276955,María Antonio Vargas Mejía,Plaza Lima Norte,Utiles Escolares,Asesor de Ventas,Depto Útiles,2024-12-14,2026-03-09,Voluntario
3,906024,Álvaro Castillo Aguilar,Plaza Lima Norte,ÚTILES ESCOLARES,Asesor de Ventas,Depto Útiles,2025-07-03,2026-03-04,Fin de contrato
4,10809497,Kevin Gabriela Vega Carranza,plaza lima norte,MODA,Cajero,Caja,2024-08-21,2026-03-25,Voluntario

In [14]:
dotacion.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2033 entries, 0 to 2032
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   dni            2033 non-null   int64
 1   nombre         2033 non-null   object
 2   tienda         2033 non-null   object
 3   vertical       2033 non-null   object
 4   puesto         2033 non-null   object
 5   departamento   2033 non-null   object
 6   fecha_ingreso  2033 non-null   object
 7   fecha_cese     110 non-null    object
 8   tipo_salida    110 non-null    object
dtypes: int64(1), object(8)
memory usage: 143.1+ KB

In [15]:
# transofmramos dni
dotacion["dni"] = dotacion["dni"].astype("string")

In [16]:
dotacion.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2033 entries, 0 to 2032
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   dni            2033 non-null   string
 1   nombre         2033 non-null   object
 2   tienda         2033 non-null   object
 3   vertical       2033 non-null   object
 4   puesto         2033 non-null   object
 5   departamento   2033 non-null   object
 6   fecha_ingreso  2033 non-null   object
 7   fecha_cese     110 non-null    object
 8   tipo_salida    110 non-null    object
dtypes: object(8), string(1)
memory usage: 143.1+ KB

In [17]:
# cermaos una columna dicional para ver el dni
dotacion["longitud_doc"] = dotacion["dni"].str.len().astype("Int64")

In [18]:
dotacion["longitud_doc"].value_counts(dropna=False).sort_index()

longitud_doc
4       3
5      20
6     279
7     467
8    1264
Name: count, dtype: Int64

In [19]:
mask = (dotacion["longitud_doc"] == 4) 
dotacion.loc[mask, "dni"] = "0000" + dotacion.loc[mask, "dni"] 
# Recalcular longitud_doc para esos casos
dotacion.loc[mask, "longitud_doc"] = dotacion.loc[mask, "dni"].str.len()

In [20]:
dotacion["longitud_doc"].value_counts(dropna=False)

longitud_doc
8    1267
7     467
6     279
5      20
Name: count, dtype: Int64

In [21]:
# ahor para 5 digitos
mask = (dotacion["longitud_doc"] == 5) 
dotacion.loc[mask, "dni"] = "000" + dotacion.loc[mask, "dni"] 
# Recalcular longitud_doc para esos casos
dotacion.loc[mask, "longitud_doc"] = dotacion.loc[mask, "dni"].str.len()

In [22]:
dotacion["longitud_doc"].value_counts(dropna=False)

longitud_doc
8    1287
7     467
6     279
Name: count, dtype: Int64

In [23]:
# ahora para 6 digitos
mask = (dotacion["longitud_doc"] == 6) 
dotacion.loc[mask, "dni"] = "00" + dotacion.loc[mask, "dni"] 
# Recalcular longitud_doc para esos casos
dotacion.loc[mask, "longitud_doc"] = dotacion.loc[mask, "dni"].str.len()

In [24]:
# parata 7 digitos
mask = (dotacion["longitud_doc"] == 7) 
dotacion.loc[mask, "dni"] = "0" + dotacion.loc[mask, "dni"] 
# Recalcular longitud_doc para esos casos
dotacion.loc[mask, "longitud_doc"] = dotacion.loc[mask, "dni"].str.len()

In [25]:
dotacion["longitud_doc"].value_counts(dropna=False)

longitud_doc
8    2033
Name: count, dtype: Int64

In [26]:
# Numero de registros de dnis - registrados
len(dotacion["dni"])

2033

In [27]:
# registros unicos
dotacion["dni"].nunique()

1997

In [28]:
#eliminamos duplicados

In [29]:
dotacion = dotacion.drop_duplicates(subset=["dni"])

In [30]:
len(dotacion["dni"])

1997

In [31]:
dotacion["dni"].nunique()

1997

In [32]:
# subsanado este error

In [33]:
dotacion["tienda"].value_counts(dropna=True)

tienda
Plaza Lima Norte    214
Jockey Plaza        199
Mall del Sur        198
Salaverry           110
Angamos             109
Bellavista          105
San Isidro           91
La Molina            89
 Jockey Plaza        38
Plza Lima Norte      37
JOCKEY PLAZA         37
Mall del sur         37
JockeyPlaza          37
 Plaza Lima Nte      35
PLAZA LIMA NORTE     35
Mall d Sur           34
Plaza Lima Nte       34
mall del sur         33
Mall Sur             33
Jokey Plaza          32
plaza lima norte     30
Jockey Pza           29
Sn Isidro            27
 MALL DEL SUR        26
bellavista           24
San Isidro           22
 BELLAVISTA          21
Bellavsta            21
Bella Vista          21
Salaverri            20
 LA MOLINA           19
angamos              19
Salavery             19
 SALAVERRY           19
Angámos              18
salaverry            18
la molina            18
San isidro           18
 Angamos             17
La molina            17
Molina               16
ANGAMOS              11
 SAN ISIDRO          10
Name: count, dtype: int64

In [34]:
# Estandraizacion de los nombres

In [35]:
dotacion["tienda"] = dotacion["tienda"].astype("string")

In [36]:
dotacion["tienda"] = dotacion["tienda"].str.strip() # quita espacios
dotacion["tienda"] = dotacion["tienda"].str.lower() # todo em minus
dotacion["tienda"] = dotacion["tienda"].str.replace(r"\s+", " ", regex=True) # quitamos espacios doble o triples

In [37]:
dotacion["tienda"] = (
    dotacion["tienda"]
    .str.normalize("NFKD")
    .str.encode("ascii", errors="ignore")
    .str.decode("utf-8")
)

In [38]:
dotacion["tienda"].value_counts(dropna=True)

tienda
mall del sur        294
plaza lima norte    279
jockey plaza        274
angamos             174
bellavista          150
salaverry           147
la molina           143
san isidro          141
plaza lima nte       69
jockeyplaza          37
plza lima norte      37
mall d sur           34
mall sur             33
jokey plaza          32
jockey pza           29
sn isidro            27
bellavsta            21
bella vista          21
salaverri            20
salavery             19
molina               16
Name: count, dtype: int64

In [39]:
dotacion["tienda"] = dotacion["tienda"].replace({
    "plza lima norte": "plaza lima norte",
    "bellavsta": "bellavista",
    "salaverri": "salaverry",
    "salavery": "salaverry",
    "jokey plaza": "jockey plaza",
    "mall d sur": "mall del sur",
    "mall sur": "mall del sur",
    "san isidro,": "san isidro"
})

In [40]:
dotacion["tienda"].value_counts(dropna=True)

tienda
mall del sur        361
plaza lima norte    316
jockey plaza        306
salaverry           186
angamos             174
bellavista          171
la molina           143
san isidro          141
plaza lima nte       69
jockeyplaza          37
jockey pza           29
sn isidro            27
bella vista          21
molina               16
Name: count, dtype: int64

In [41]:
dotacion["tienda"] = dotacion["tienda"].replace({
    "sn isidro": "san isidro",
    "jockeyplaza": "jockey plaza",
    "jockey pza": "jockey plaza"
    
})

In [42]:
dotacion["tienda"].value_counts(dropna=True)

tienda
jockey plaza        372
mall del sur        361
plaza lima norte    316
salaverry           186
angamos             174
bellavista          171
san isidro          168
la molina           143
plaza lima nte       69
bella vista          21
molina               16
Name: count, dtype: int64

In [43]:
dotacion["tienda"] = dotacion["tienda"].replace({
    
    "plaza lima nte": "plaza lima norte"
    
})

In [44]:
dotacion["tienda"].value_counts(dropna=True)

tienda
plaza lima norte    385
jockey plaza        372
mall del sur        361
salaverry           186
angamos             174
bellavista          171
san isidro          168
la molina           143
bella vista          21
molina               16
Name: count, dtype: int64

In [45]:
dotacion["tienda"] = dotacion["tienda"].str.title()

In [46]:
dotacion["tienda"].value_counts(dropna=True)

tienda
Plaza Lima Norte    385
Jockey Plaza        372
Mall Del Sur        361
Salaverry           186
Angamos             174
Bellavista          171
San Isidro          168
La Molina           143
Bella Vista          21
Molina               16
Name: count, dtype: int64

#### Vertical

In [47]:
dotacion["vertical"].value_counts(dropna=True)

vertical
Útiles Escolares    353
Moda                278
Tecnología          234
Hogar               218
Útiles Escolar       63
Utiles Escol.        60
útiles escolares     57
Utiles Escolares     53
ÚTILES ESCOLARES     53
 moda                50
 MODA                48
Utiles escolar       48
HOGAR                47
Tecnologia           44
 Tecnologia          42
Moda                 41
 Hogr                40
Tecnológia           37
hogar                37
Mda                  35
TECNOLOGIA           34
 tecnologia          33
Hogar                31
moda                 31
 hogar               30
Name: count, dtype: int64

In [48]:
dotacion["vertical"] = dotacion["vertical"].astype("string")
dotacion["vertical"] = dotacion["vertical"].str.strip() # quita espacios
dotacion["vertical"] = dotacion["vertical"].str.lower() # todo em minus
dotacion["vertical"] = dotacion["vertical"].str.replace(r"\s+", " ", regex=True) # quitamos espacios doble o triples
dotacion["vertical"] = (
    dotacion["vertical"]
    .str.normalize("NFKD")
    .str.encode("ascii", errors="ignore")
    .str.decode("utf-8")
)

In [49]:
dotacion["vertical"].value_counts(dropna=True)

vertical
utiles escolares    516
moda                448
tecnologia          424
hogar               363
utiles escolar      111
utiles escol.        60
hogr                 40
mda                  35
Name: count, dtype: int64

In [50]:
dotacion["vertical"] = dotacion["vertical"].replace({
    "utiles escolar": "utiles escolares",
    "utiles escol.": "utiles escolares",
    "mda": "moda"
})

In [51]:
dotacion["vertical"].value_counts(dropna=True)

vertical
utiles escolares    687
moda                483
tecnologia          424
hogar               363
hogr                 40
Name: count, dtype: int64

In [52]:
dotacion["vertical"] = dotacion["vertical"].replace({
   
    "hogr": "hogar"
})

In [53]:
dotacion["vertical"].value_counts(dropna=True)

vertical
utiles escolares    687
moda                483
tecnologia          424
hogar               403
Name: count, dtype: int64

In [54]:
dotacion["vertical"] = dotacion["vertical"].str.title()

In [55]:
dotacion["vertical"].value_counts(dropna=True)

vertical
Utiles Escolares    687
Moda                483
Tecnologia          424
Hogar               403
Name: count, dtype: int64

#### Puesto

In [56]:
dotacion["puesto"].value_counts(dropna=True)

puesto
Asesor de Ventas              785
Asesor Venta                  169
Asesor de venta               150
Vendedor de piso              146
Asesora de ventas             141
Venddor piso                  129
Cajero                        105
Auxiliar Logístico             65
Servicio al Cliente            54
Prevención                     34
Cajero(a)                      25
Visual Merchandising           23
Asistente de caja              15
Cajero                         14
Aux logístico                  14
Aux Log                        14
Asistente servicio cliente     13
Caja                           12
Auxiliar de logística          11
Servicio cliente               10
Cajer@                         10
Serv. al cliente                9
Aux. Logistica                  9
Agte prevencion                 9
Prevencionista                  8
VM                              4
Asesor SAC                      4
Prevención tienda               4
Agente de Prevención            3
Visual merch                    3
Visual Merchandiser             3
Visual M.                       2
Name: count, dtype: int64

In [57]:
dotacion["puesto"] = dotacion["puesto"].astype("string")
dotacion["puesto"] = dotacion["puesto"].str.strip() # quita espacios
dotacion["puesto"] = dotacion["puesto"].str.lower() # todo em minus
dotacion["puesto"] = dotacion["puesto"].str.replace(r"\s+", " ", regex=True) # quitamos espacios doble o triples
dotacion["puesto"] = (
    dotacion["puesto"]
    .str.normalize("NFKD")
    .str.encode("ascii", errors="ignore")
    .str.decode("utf-8")
)

In [58]:
dotacion["puesto"].value_counts(dropna=True)

puesto
asesor de ventas              785
asesor venta                  169
asesor de venta               150
vendedor de piso              146
asesora de ventas             141
venddor piso                  129
cajero                        119
auxiliar logistico             65
servicio al cliente            54
prevencion                     34
cajero(a)                      25
visual merchandising           23
asistente de caja              15
aux logistico                  14
aux log                        14
asistente servicio cliente     13
caja                           12
auxiliar de logistica          11
servicio cliente               10
cajer@                         10
serv. al cliente                9
aux. logistica                  9
agte prevencion                 9
prevencionista                  8
vm                              4
asesor sac                      4
prevencion tienda               4
agente de prevencion            3
visual merch                    3
visual merchandiser             3
visual m.                       2
Name: count, dtype: int64

In [59]:
dotacion["puesto"] = dotacion["puesto"].replace({
    "asesor de venta": "asesor de ventas",
    "asesor venta": "asesor de ventas",
    "asesora de ventas": "asesor de ventas",
    "visual merch": "visual merchandising",
    "visual m.": "visual merchandising ",
    "visual merchandiser": "visual merchandising"
})

In [60]:
dotacion["puesto"].value_counts(dropna=True)

puesto
asesor de ventas              1245
vendedor de piso               146
venddor piso                   129
cajero                         119
auxiliar logistico              65
servicio al cliente             54
prevencion                      34
visual merchandising            29
cajero(a)                       25
asistente de caja               15
aux log                         14
aux logistico                   14
asistente servicio cliente      13
caja                            12
auxiliar de logistica           11
servicio cliente                10
cajer@                          10
serv. al cliente                 9
agte prevencion                  9
aux. logistica                   9
prevencionista                   8
asesor sac                       4
vm                               4
prevencion tienda                4
agente de prevencion             3
visual merchandising             2
Name: count, dtype: int64

In [61]:
dotacion["puesto"] = dotacion["puesto"].replace({

    "visual merch": "visual merchandising",
    "visual m.": "visual merchandising"
})

In [62]:
dotacion["puesto"].value_counts(dropna=True)

puesto
asesor de ventas              1245
vendedor de piso               146
venddor piso                   129
cajero                         119
auxiliar logistico              65
servicio al cliente             54
prevencion                      34
visual merchandising            29
cajero(a)                       25
asistente de caja               15
aux log                         14
aux logistico                   14
asistente servicio cliente      13
caja                            12
auxiliar de logistica           11
servicio cliente                10
cajer@                          10
serv. al cliente                 9
agte prevencion                  9
aux. logistica                   9
prevencionista                   8
asesor sac                       4
vm                               4
prevencion tienda                4
agente de prevencion             3
visual merchandising             2
Name: count, dtype: int64

In [63]:
dotacion["puesto"] = dotacion["puesto"].replace({

    "venddor piso": "vendedor de piso",
    "aux log": "auxiliar de logistica",
    "aux logistico": "auxiliar de logistica",
    "caja": "cajero(a)",
    "auxiliar logistico": "auxiliar de logistica",
})

In [64]:
dotacion["puesto"].value_counts(dropna=True)

puesto
asesor de ventas              1245
vendedor de piso               275
cajero                         119
auxiliar de logistica          104
servicio al cliente             54
cajero(a)                       37
prevencion                      34
visual merchandising            29
asistente de caja               15
asistente servicio cliente      13
servicio cliente                10
cajer@                          10
serv. al cliente                 9
agte prevencion                  9
aux. logistica                   9
prevencionista                   8
asesor sac                       4
vm                               4
prevencion tienda                4
agente de prevencion             3
visual merchandising             2
Name: count, dtype: int64

In [65]:
dotacion["puesto"] = dotacion["puesto"].replace({

    "cajero": "cajero(a)",
    "vm": "visual merchandising",
    "asesor sac": "asistente servicio cliente",
    "serv. al cliente": "asistente servicio cliente",
    "agte prevencion": "prevencionista",
    "agente de prevencion": "prevencionista"
})

In [66]:
dotacion["puesto"].value_counts(dropna=True)

puesto
asesor de ventas              1245
vendedor de piso               275
cajero(a)                      156
auxiliar de logistica          104
servicio al cliente             54
prevencion                      34
visual merchandising            33
asistente servicio cliente      26
prevencionista                  20
asistente de caja               15
servicio cliente                10
cajer@                          10
aux. logistica                   9
prevencion tienda                4
visual merchandising             2
Name: count, dtype: int64

In [67]:
dotacion["puesto"] = dotacion["puesto"].replace({

    "aux. logistica": "auxiliar de logistica",
    "prevencion": "prevencionista",
    "cajer@": "cajero(a)"
})

In [68]:
dotacion["puesto"].value_counts(dropna=True)

puesto
asesor de ventas              1245
vendedor de piso               275
cajero(a)                      166
auxiliar de logistica          113
servicio al cliente             54
prevencionista                  54
visual merchandising            33
asistente servicio cliente      26
asistente de caja               15
servicio cliente                10
prevencion tienda                4
visual merchandising             2
Name: count, dtype: int64

In [69]:
dotacion["puesto"] = dotacion["puesto"].replace({

    "servicio cliente": "asistente servicio cliente",
    "servicio al cliente": "asistente servicio cliente"
})

In [70]:
dotacion["puesto"].value_counts(dropna=True)

puesto
asesor de ventas              1245
vendedor de piso               275
cajero(a)                      166
auxiliar de logistica          113
asistente servicio cliente      90
prevencionista                  54
visual merchandising            33
asistente de caja               15
prevencion tienda                4
visual merchandising             2
Name: count, dtype: int64

In [71]:
dotacion["puesto"] = dotacion["puesto"].replace({

    "visual merchandising ": "visual merchandising",
    "prevencion tienda": "prevencionista"
})

In [72]:
dotacion["puesto"].value_counts(dropna=True)

puesto
asesor de ventas              1245
vendedor de piso               275
cajero(a)                      166
auxiliar de logistica          113
asistente servicio cliente      90
prevencionista                  58
visual merchandising            35
asistente de caja               15
Name: count, dtype: int64

In [73]:
dotacion["puesto"] = dotacion["puesto"].str.title()

In [74]:
dotacion["puesto"].value_counts(dropna=True)

puesto
Asesor De Ventas              1245
Vendedor De Piso               275
Cajero(A)                      166
Auxiliar De Logistica          113
Asistente Servicio Cliente      90
Prevencionista                  58
Visual Merchandising            35
Asistente De Caja               15
Name: count, dtype: int64

#### Departamentos

In [75]:
dotacion["departamento"].value_counts(dropna=True)

departamento
Útiles Escolares        294
Ventas Moda             202
Ventas Tecnología       189
Ventas Hogar            167
Caja                    106
Logística                74
Servicio Cliente         65
Útiles escolar           54
utiles escolares         52
Dpto. Utiles             46
Depto Útiles             45
Utiles Escolares         45
Ventas Moda              42
ventas moda              39
VENTAS MODA              38
ventas moda              36
ÚTILES ESCOLARES         35
Prevención               34
ventas hogar             34
VENTAS TECNOLOGIA        33
CAJA                     32
Vtas Tecnologia          30
Vtas Hogar               30
Ventas Hogar             29
ventas tecnologia        27
Ventas Tecnología        27
VENTAS HOGAR             26
Visual Merchandising     23
Caja                     22
Cajas                    21
 logistica               15
Logistica                11
Serv. Cliente            10
LOGISTICA                 8
prevencion                8
Servicio cliente          8
SERVICIO CLIENTE          7
Prevención                7
PREVENCION                6
Logístca                  5
VISUAL MERCH              5
Visual M.                 5
sac                       3
Visual merchandising      2
Name: count, dtype: int64

In [76]:
dotacion["departamento"] = dotacion["departamento"].astype("string")
dotacion["departamento"] = dotacion["departamento"].str.strip()  
dotacion["departamento"] = dotacion["departamento"].str.lower()  
dotacion["departamento"] = dotacion["departamento"].str.replace(r"\s+", " ", regex=True)  
dotacion["departamento"] = (
    dotacion["departamento"]
    .str.normalize("NFKD")
    .str.encode("ascii", errors="ignore")
    .str.decode("utf-8")
)

In [77]:
dotacion["departamento"].value_counts(dropna=True)

departamento
utiles escolares        426
ventas moda             357
ventas tecnologia       276
ventas hogar            256
caja                    160
logistica               108
servicio cliente         80
prevencion               55
utiles escolar           54
dpto. utiles             46
depto utiles             45
vtas tecnologia          30
vtas hogar               30
visual merchandising     25
cajas                    21
serv. cliente            10
logistca                  5
visual m.                 5
visual merch              5
sac                       3
Name: count, dtype: int64

In [78]:
dotacion["departamento"] = dotacion["departamento"].replace({
    "utiles escolar": "utiles escolares",
    "dpto. utiles": "utiles escolares",
    "depto utiles": "utiles escolares",
    "vtas tecnologia": "ventas tecnologia",
    "vtas hogar": "ventas hogar",
    "serv. cliente": "servicio cliente",
    "visual m.": "visual merch",
    "cajas": "caja",
    "sac": "caja"
})

In [79]:
dotacion["departamento"].value_counts(dropna=True)

departamento
utiles escolares        571
ventas moda             357
ventas tecnologia       306
ventas hogar            286
caja                    184
logistica               108
servicio cliente         90
prevencion               55
visual merchandising     25
visual merch             10
logistca                  5
Name: count, dtype: int64

In [80]:
dotacion["departamento"] = dotacion["departamento"].replace({
    "visual merch": "visual merchandising",
    "logistca": "logistica"
})

In [81]:
dotacion["departamento"].value_counts(dropna=True)

departamento
utiles escolares        571
ventas moda             357
ventas tecnologia       306
ventas hogar            286
caja                    184
logistica               113
servicio cliente         90
prevencion               55
visual merchandising     35
Name: count, dtype: int64

In [82]:
dotacion["departamento"] = dotacion["departamento"].str.title()

In [83]:
dotacion["departamento"].value_counts(dropna=True)

departamento
Utiles Escolares        571
Ventas Moda             357
Ventas Tecnologia       306
Ventas Hogar            286
Caja                    184
Logistica               113
Servicio Cliente         90
Prevencion               55
Visual Merchandising     35
Name: count, dtype: int64

In [84]:
len(dotacion["departamento"].unique())

9

In [85]:
len(dotacion["departamento"].value_counts(dropna=True))

9

In [86]:
diccionario

  departamento_original           gerencia_homologada
0          Ventas Hogar            Gerencia Comercial
1           Ventas Moda            Gerencia Comercial
2     Ventas Tecnología            Gerencia Comercial
3  Visual Merchandising            Gerencia Comercial
4   Servicio al Cliente  Gerencia Experiencia Cliente
5                 Cajas          Gerencia Operaciones
6             Logística          Gerencia Operaciones
7            Prevención          Gerencia Operaciones
8      Utiles Escolares            Gerencia Comercial

In [87]:
# Alineación de acuerdo al diccionario

In [88]:
dotacion["departamento"] = dotacion["departamento"].replace({
    "Ventas Tecnologia": "Ventas Tecnología",
    "Servicio Cliente": "Servicio al Cliente",
    "Caja": "Cajas",
    "Logistica": "Logística",
    "Prevencion": "Prevención"
})

In [89]:
dotacion["departamento"].value_counts(dropna=True)

departamento
Utiles Escolares        571
Ventas Moda             357
Ventas Tecnología       306
Ventas Hogar            286
Cajas                   184
Logística               113
Servicio al Cliente      90
Prevención               55
Visual Merchandising     35
Name: count, dtype: int64

In [90]:
dotacion = dotacion.merge(
    diccionario[["departamento_original", "gerencia_homologada"]],
    left_on="departamento",
    right_on="departamento_original",
    how="left"
)

In [91]:
dotacion.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1997 entries, 0 to 1996
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   dni                    1997 non-null   string
 1   nombre                 1997 non-null   object
 2   tienda                 1997 non-null   object
 3   vertical               1997 non-null   object
 4   puesto                 1997 non-null   object
 5   departamento           1997 non-null   object
 6   fecha_ingreso          1997 non-null   object
 7   fecha_cese             105 non-null    object
 8   tipo_salida            105 non-null    object
 9   longitud_doc           1997 non-null   Int64
 10  departamento_original  1997 non-null   object
 11  gerencia_homologada    1997 non-null   object
dtypes: Int64(1), object(10), string(1)
memory usage: 189.3+ KB

In [92]:
dotacion

,dni,nombre,tienda,vertical,puesto,departamento,fecha_ingreso,fecha_cese,tipo_salida,longitud_doc,departamento_original,gerencia_homologada
0,99510741,Diego Elena Ramírez Flores,Plaza Lima Norte,Hogar,Asesor De Ventas,Ventas Hogar,2024-05-22,2026-03-24,Voluntario,8,Ventas Hogar,Gerencia Comercial
1,87326012,Daniela Eduardo Carranza Medina,Plaza Lima Norte,Utiles Escolares,Asesor De Ventas,Utiles Escolares,2024-01-28,2026-03-18,Voluntario,8,Utiles Escolares,Gerencia Comercial
2,00276955,María Antonio Vargas Mejía,Plaza Lima Norte,Utiles Escolares,Asesor De Ventas,Utiles Escolares,2024-12-14,2026-03-09,Voluntario,8,Utiles Escolares,Gerencia Comercial
3,00906024,Álvaro Castillo Aguilar,Plaza Lima Norte,Utiles Escolares,Asesor De Ventas,Utiles Escolares,2025-07-03,2026-03-04,Fin de contrato,8,Utiles Escolares,Gerencia Comercial
4,10809497,Kevin Gabriela Vega Carranza,Plaza Lima Norte,Moda,Cajero(A),Cajas,2024-08-21,2026-03-25,Voluntario,8,Cajas,Gerencia Operaciones
...,...,...,...,...,...,...,...,...,...,...,...,...
1992,04018832,Lucía Isabel Cruz Chávez,Salaverry,Hogar,Vendedor De Piso,Ventas Hogar,2025-10-15,NaN,NaN,8,Ventas Hogar,Gerencia Comercial
1993,00298463,Renzo Gabriela Campos Mendoza,Salaverry,Utiles Escolares,Asesor De Ventas,Utiles Escolares,2025-11-05,NaN,NaN,8,Utiles Escolares,Gerencia Comercial
1994,00685082,Sebastián Elena Vega Herrera,Salaverry,Moda,Asesor De Ventas,Ventas Moda,2025-12-07,NaN,NaN,8,Ventas Moda,Gerencia Comercial
1995,94054802,Diego Patricia Mejía Castillo,Salaverry,Moda,Asesor De Ventas,Ventas Moda,2025-08-04,NaN,NaN,8,Ventas Moda,Gerencia Comercial
1996,37370260,Karen Antonio Valdivia Morales,Salaverry,Hogar,Vendedor De Piso,Ventas Hogar,2025-09-19,NaN,NaN,8,Ventas Hogar,Gerencia Comercial

#### Finalización del ETL ####

In [93]:
#### Base Limpia y escturarada para la visuzalización en power Bi

In [94]:
dotacion.to_csv("dotacion_final.txt", sep="|", index=False)

In [95]:
remuneracion.to_csv("remuneracion_final.txt", sep="|", index=False)